In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("loan_data.csv")

In [3]:
dataset.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [4]:
dataset.isnull().sum()

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace = True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_26028\1904562844.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace = True)

In [6]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [7]:
#method 1 using get_dummies() to perform one hot encoder

In [8]:
en_data = dataset[["Gender","Married"]]
en_data

     Gender Married
0      Male     Yes
1      Male     Yes
2      Male     Yes
3      Male      No
4      Male     Yes
..      ...     ...
376    Male     Yes
377    Male     Yes
378  Female      No
379    Male     Yes
380  Female      No

[381 rows x 2 columns]

In [9]:
pd.get_dummies(en_data)

     Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True       False         True
1            False         True       False         True
2            False         True       False         True
3            False         True        True        False
4            False         True       False         True
..             ...          ...         ...          ...
376          False         True       False         True
377          False         True       False         True
378           True        False        True        False
379          False         True       False         True
380           True        False        True        False

[381 rows x 4 columns]

In [10]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  381 non-null    bool
 1   Gender_Male    381 non-null    bool
 2   Married_No     381 non-null    bool
 3   Married_Yes    381 non-null    bool
dtypes: bool(4)
memory usage: 1.6 KB

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
ohe = OneHotEncoder(drop="first")
ar = ohe.fit_transform(en_data).toarray()

In [20]:
pd.DataFrame(ar,columns = ["Gender_Male","Married_Yes"])

     Gender_Male  Married_Yes
0            1.0          1.0
1            1.0          1.0
2            1.0          1.0
3            1.0          0.0
4            1.0          1.0
..           ...          ...
376          1.0          1.0
377          1.0          1.0
378          0.0          0.0
379          1.0          1.0
380          0.0          0.0

[381 rows x 2 columns]