In [1]:
# Using Cyclic Line Function

In [ ]:
import pandas as pd

In [3]:
df = pd.DataFrame({"Size":["s","m","l","xl","s","m","l","s","s","l","xl","m"]})
df.head()

  Size
0    s
1    m
2    l
3   xl
4    s

In [4]:
ord_data = [["s","m","l","xl"]]

In [5]:
from sklearn.preprocessing import OrdinalEncoder

In [6]:
oe = OrdinalEncoder(categories = ord_data)
oe.fit(df[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [7]:
df["Size_en"]  = oe.transform(df[["Size"]])

In [8]:
df

   Size  Size_en
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0

In [9]:
## Using Map Function

In [10]:
ord_data1 = {"s":0,"m":1,"l":2,"xl":3}

In [11]:
df["Size_en_map"] = df["Size"].map(ord_data1)

In [12]:
df

   Size  Size_en  Size_en_map
0     s      0.0            0
1     m      1.0            1
2     l      2.0            2
3    xl      3.0            3
4     s      0.0            0
5     m      1.0            1
6     l      2.0            2
7     s      0.0            0
8     s      0.0            0
9     l      2.0            2
10   xl      3.0            3
11    m      1.0            1

In [13]:
dataset = pd.read_csv("loan_data.csv")

In [14]:
dataset.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [16]:
dataset["Property_Area"].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)

In [17]:
en_data_ord = [['Rural', 'Urban', 'Semiurban']]

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
oen = OrdinalEncoder(categories=en_data_ord)
oen

OrdinalEncoder(categories=[['Rural', 'Urban', 'Semiurban']])

In [21]:
dataset["Property_Area"] = oen.fit_transform(dataset[["Property_Area"]])

In [23]:
dataset.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,1.0,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,1.0,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,1.0,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,1.0,Y